### PR TITLE
draft of kappa, CCN crit R and sat

### PR DESCRIPTION
**Pull request by Gorkowski**
Start of kappa calculation to get CCN activation radius and water saturation ratio.

I tried to be general, and where possible, this can be reused for organic equilibrium. 

TODO: tests and units on inputs.

### CODE REVIEW

**Comment by Gorkowski** [comment]
Sending arrays to `particle_h2o_activation` doesn't work due to the fmin solver. 

I'm still not sure if you would need to do this iteratively in a parcel-like simulation or just once or not at all.

**Comment by ngam** [comment]
We will extend it to arrays later. I am sure there is a way to do it

**Comment by Gorkowski** [comment]
also I don't understand that flake8 error `./parcelona/test/util_kelvin_radius_test.py:11:1: E303 too many blank lines (3)`

**Comment by ngam** [comment]
Could you try format document locally? I will do that now if not

**Comment by ngam** [comment]
right click > format document (in vscode)

**Comment by ngam** [comment]
You added an extra line in an unrelated file in [e99d7c5](https://github.com/uncscode/parcelona/pull/8/commits/e99d7c50d4ede55edec8799140c781b3b417fcc5)

**Review by ngam — APPROVED** [review]

**Comment by ngam** [comment]
Should I merge this?

**Comment by ngam** [comment]
The one thing that's still quite unclear to me is how do we get the "wet radius" exactly?

**Comment by Gorkowski** [comment]
> The one thing that's still quite unclear to me is how do we get the "wet radius" exactly?

That is a problem. At t=0 wet and dry radius are equal. The condensation driving force would be the difference between the water activity gas-phase and kelvin-adjusted water activity in the particle phase. (or I think that is it). For this, I think we just want `particle_effective_activity` vs RH

The critical sat and radius `particle_h2o_activation`, I wanted them for diagnostics. So given a distribution and saturation ratio. You can calculate how many of the particles would activate (like in a CCNc counter). I'm not sure why `pyrcel` used it.

**Comment by ngam** [comment]
My understanding was that kappa would get us the amount of water to add to the particle and then you can calculate the wet radius. Meaning: the wet radius is basically what the particle would look like if we let it reach thermodynamic equilibrium with the water available around it.

It is okay though, I am still getting my head around this. I think we are getting there. I am just trying to map everything to think about how to move the code pieces within a solver and this is a piece that still bothers me... we somehow need to know the wet radius from the dry radius... I often only think about the dry radius

**Comment by ngam** [comment]
Merging this. We will revisit and improve, but a step forward! Thanks @Gorkowski!!

**Pull request merged**
